### ISSUE TITLE
Gab on pages that does not include the widget

### ISSUE THREAD

**Issue by MPStranger** [Codestag/stag-custom-sidebars#6]
Hi, First of all, I have to say I really love this plugin.

I only have one issue with the plugin. This is the scenario:
I use one widget that I show on all pages in the header.
However each item (ie text, userdefined menu etc.) I add to the widget, I also change the visability.
One item I only show on front page, one item I only show on product pages and one item I only show on posts etc. This option is what I really love.

However, for each item I add, the plugin adds an empty space in the header on all pages where the item is NOT shown.

Example: I have two items that is NOT shown on the front page, and only one item that IS.
On the front page I then see a break in the header (equal to <br><br>) and my guess is that it is shown due to the two items NOT being visible on the front page.

It would be so cool if these breaks could be removed. Because this plugin literally gives me the option to show whatever I like in the header. The problem is however, if I have 10 items not being show on most pages, those pages will all have a huge gap equal to 10 <br>'s

Hope this makes sense, otherwise please let me know.

Thanks

**Comment by mauryaratan** [comment]
Hey @MPStranger, thanks for the details. I could, however, use a live example to see what's really going on there. Could you provide your site URL for me to take a look? Thanks 👍
